### ISSUE TITLE
Instructions for running directly from ADB shell

### ISSUE THREAD

**Issue by Fusionette** [MolotovCherry/Android-ImageMagick7#74]
This is not really an issue, but rather a would-be Wiki article if this repo had a wiki, or maybe there should be a section in the readme for people who just want to use this tool from the adb shell, and not embed it in an application. I've seen multiple (closed) issues asking for this, so there's clearly interest.

- Download the static zip file and extract it. You will have a folder with 3 files: `libc++_shared.so`, `libomp.so` and `magick`.
- Use ADB to put those files in a path where files can be executed from. The home path and the sdcard **are not valid locations**. For this example, I put the three files in a folder called `magick` and then ran `adb push magick /data/local/tmp` to push the whole folder into `/data/local/tmp/magick`
- Run `adb shell` to get to the command line, and then change to the path where the files reside, and set the binary as executable:
    - `cd /data/local/tmp/magick`
    - `chmod 0755 magick`
- If you try to run `./magick` now, it will not work because it can't find the library path. You need to set up the environment variables:
    - `export TMPDIR=/data/local/tmp`
    - `export MAGICK_HOME=/data/local/tmp/magick`
    - `export LD_LIBRARY_PATH=/data/local/tmp/magick`
- You can now run `./magick` and it will give you the usage instructions. For example, this will capture the screen and then create a new PNG file with the 32x32 box at 500,500:
    - `screencap -p screen.png`
    - `./magick screen.png -crop 32x32+500+500 crop.png`

Obviously setting up the environment variables every time would get tedious, so you should use a shell script for this.

**Comment by cherryleafroad** [comment]
Thanks for the write-up! You can also use termux to achieve a similar effect (adding env vars of course). I'm not sure how termux behaves on Android 10+ though due to the executable permissions being denied unless it's in the lib directory

**Comment by Fusionette** [comment]
Termux is not great if you're trying to use this for automated testing. My use case is that I load an application and use `adb shell input tap` and `adb shell input touchscreen swipe` to select and click on various UI elements, and I use screencap and imagemagick to display the results (as well as crop little bits of the screen to validate where I am before I send more inputs). Termux is its own isolated shell as far as I know, not accessible from ADB.

**Comment by cherryleafroad** [comment]
That makes sense. Yeah, for testing your app you definitely need to do it in a way like that. Terms is definitely a no go for that.

I'll think about revamping the readme and organizing the content into pages, including the info you just provided for testing it

**Comment by MolotovCherry** [comment]
Thanks for your contribution. I've added the wiki pages now along with your instructions. 😄
