### ISSUE TITLE
how to use this software?

### ISSUE THREAD

**Issue by kucingkembar** [MolotovCherry/Android-ImageMagick7#87]
Sorry for my bad English and using issue, I don't understand how to use discussion
I like to use ImageMagick "convert" to split images that downloaded from tachiyomi
because some comic pages have long-strips that slowing down the android,
i usually move the file from android, do this code
`for /r "%~dp0" %%x in (*.jpg) do convert -crop 100%x50% "%~1" "%~dpn1_CR%~x1"`
then move back to android,

i don't understand how to do this,
can you do something about it,
my question is: how to do this on android

anyway this my android spec
```
OS 	Android 6.0.1 (Marshmallow), MIUI 9.2
Chipset 	Qualcomm MSM8937 Snapdragon 430 (28 nm)
CPU 	Octa-core 1.4 GHz Cortex-A53
GPU 	Adreno 505
```
thank you for reading, have a nice day

**Comment by MolotovCherry** [comment]
- `convert` is a symlink to `magick`
- `for /r "%~dp0" %%x in (*.jpg) do` is batch (windows), you should convert this to shell or something you can use on your own android terminal
- use an android terminal like termux and [read the setup page on the wiki](https://github.com/MolotovCherry/Android-ImageMagick7/wiki/Setup--&--building-instructions)
- If you use termux, you might as well use the imagemagick package they already have and skip this library.

This library is mostly meant for Android development anyways.

**Comment by kucingkembar** [comment]
thank for the quick reply, can I have the APK?

**Comment by MolotovCherry** [comment]
This is a library (not app). It's meant for people to use in developing their own apps. If you'd like something easy, you can try termux off of the play store and install the imagemagick package and use it from the commandline on your device

**Comment by kucingkembar** [comment]
ah, thank you, that what i looking for, you can close this issue
